### ISSUE TITLE
Drupal 8.9.x and Drupal 9.0.x compatibility

### ISSUE THREAD

**Issue by balazswmann** [Pronovix/swagger_ui_formatter#37]

**Comment by mxr576** [comment]
Drupal 9 cannot be installed yet because the installed version of drupal/drupal-driver (transitively required by pronovix/drupal-qa) is not compatible with Drupal 9 yet. The required version of drupal/drupal-extension has to be bumped to 2.1.0 or it should be whitelisted in pronovix/drupal-qa).

**Comment by mxr576** [comment]
and a few other adjusts have to be made... https://github.com/Pronovix/drupal-qa/compare/2.8.0...mxr576:master
