### ISSUE TITLE
Coordinate repository with Drupal.org to release Drupal 9 version and Drupal 8 and Drupal 7 updates.

### ISSUE THREAD

**Issue by VladimirAus** [Pronovix/swagger_ui_formatter#43]
Currently the module blocks upgrade to Drupal 9. 
As issue queue is blocked on drupal.org there is no proper way to provide a patch.
Is it possible to start rolling changes to drupal.org?

**Comment by mxr576** [comment]
Hi @VladimirAus,

thanks for reaching out to us. Drupal 9 compatibility is already available in the master branch: https://github.com/Pronovix/swagger_ui_formatter/blob/master/composer.json#L15 (since #37)

It is going to be available in 3.0.0 but we have still some things to wrap up first.

**Comment by nishasw** [comment]
Hi @mxr576 

Is there any timeline for this module to be available for Drupal 9 ?

**Comment by balazswmann** [comment]
Closing this issue as the Drupal 9 compatible version has been released: [8.x-3.2](https://www.drupal.org/project/swagger_ui_formatter/releases/8.x-3.2)
