### ISSUE TITLE
Not supported! Error Swagger UI Field Formatter 8.x-2.4

### ISSUE THREAD

**Issue by dhinakaran60** [Pronovix/swagger_ui_formatter#63]
After the security update of drupal core Drupal core 8.9.13

Not supported! Swagger UI Field Formatter 8.x-2.4Recommended version:8.x-3.1 (2021-Feb-05)

DownloadRelease notes
CompatibleRequires Drupal core: 8.9.13 to 9.1.4Includes:

![image](https://user-images.githubusercontent.com/65781478/107341200-b06db680-6ae4-11eb-954f-97c48e46b96c.png)

Also when i try to update 8.x.3.1

$ composer require 'drupal/swagger_ui_formatter:^3.1'
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for drupal/swagger_ui_formatter ^3.1 -> satisfiable by drupal/swagger_ui_formatter[3.1.0].
    - Conclusion: remove composer/semver 1.7.2
    - Conclusion: don't install composer/semver 1.7.2
    - drupal/swagger_ui_formatter 3.1.0 requires drupal/core-recommended ~9.1 -> satisfiable by drupal/core-recommended[9.1.0, 9.1.0-alpha1, 9.1.0-beta1, 9.1.0-rc1, 9.1.0-rc2, 9.1.0-rc3, 9.1.1, 9.1.2, 9.1.3, 9.1.4, 9.1.x-dev, 9.2.x-dev].
    - drupal/core-recommended 9.1.0-alpha1 requires composer/semver 1.7.1 -> satisfiable by composer/semver[1.7.1].
    - drupal/core-recommended 9.1.0 requires composer/semver 3.2.2 -> satisfiable by composer/semver[3.2.2].
    - drupal/core-recommended 9.1.0-beta1 requires composer/semver 3.2.2 -> satisfiable by composer/semver[3.2.2].
    - drupal/core-recommended 9.1.0-rc1 requires composer/semver 3.2.2 -> satisfiable by composer/semver[3.2.2].
    - drupal/core-recommended 9.1.0-rc2 requires composer/semver 3.2.2 -> satisfiable by composer/semver[3.2.2].
    - drupal/core-recommended 9.1.0-rc3 requires composer/semver 3.2.2 -> satisfiable by composer/semver[3.2.2].
    - drupal/core-recommended 9.1.1 requires composer/semver 3.2.2 -> satisfiable by composer/semver[3.2.2].
    - drupal/core-recommended 9.1.2 requires composer/semver 3.2.2 -> satisfiable by composer/semver[3.2.2].
    - drupal/core-recommended 9.1.3 requires composer/semver 3.2.2 -> satisfiable by composer/semver[3.2.2].
    - drupal/core-recommended 9.1.4 requires composer/semver 3.2.2 -> satisfiable by composer/semver[3.2.2].
    - drupal/core-recommended 9.1.x-dev requires composer/semver 3.2.2 -> satisfiable by composer/semver[3.2.2].
    - drupal/core-recommended 9.2.x-dev requires composer/semver 3.2.4 -> satisfiable by composer/semver[3.2.4].
    - Can only install one of: composer/semver[1.7.1, 1.7.2].
    - Can only install one of: composer/semver[3.2.2, 1.7.2].
    - Can only install one of: composer/semver[3.2.4, 1.7.2].
    - Installation request for composer/semver (locked at 1.7.2) -> satisfiable by composer/semver[1.7.2].

Installation failed, reverting ./composer.json to its original content.

Can you please help on this

**Comment by mxr576** [comment]
Tbh, I do not think this issue is related to this module directly, since Composer complains about `composer/semver` which is not a direct dependency of this module.

Try `composer require drupal/swagger_ui_formatter:^3.0 --no-update && composer update drupal/swagger_ui_formatter --with-dependencies`

**Comment by dhinakaran60** [comment]
Thanks! couple question for my clarity:

- Reason it says not supported  8.x-2.4 with drupal core security  update to 8.9.13 . due to swagger UI contributed  needs updated version in same 8.x.2.x ? may be some composer.json verion mismatch ? 
- Module version - 8.x-3.1 Requires Drupal core: 8.9.13 to 9.1.4 but in composer error i got below? is it the common error pattern and nothing to do with requires limit version ? 
   **- drupal/swagger_ui_formatter 3.0.0 requires drupal/core-recommended ~9.1 -> satisfiable by drupal/core-recommended[9.1.0, 9.1.0-alpha1, 9.1.0-beta1, 9.1.0-rc1, 9.1.0-rc2, 9.1.0-rc3, 9.1.1, 9.1.2, 9.1.3, 9.1.4, 9.1.x-dev, 9.2.x-dev].**

For your info 

I did try 

$ composer require drupal/swagger_ui_formatter:^3.0 --no-update && composer update drupal/swagger_ui_formatter --with-dependencies
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
./composer.json has been updated
Gathering patches for root package.
Loading composer repositories with package information
Warning from https://repo.packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install drupal/swagger_ui_formatter 3.1.0
    - Conclusion: remove symfony/config v3.4.47
    - Installation request for drupal/swagger_ui_formatter ^3.0 -> satisfiable by drupal/swagger_ui_formatter[3.0.0, 3.1.0].
    - Conclusion: don't install symfony/config v3.4.47
    **- drupal/swagger_ui_formatter 3.0.0 requires drupal/core-recommended ~9.1 -> satisfiable by drupal/core-recommended[9.1.0, 9.1.0-alpha1, 9.1.0-beta1, 9.1.0-rc1, 9.1.0-rc2, 9.1.0-rc3, 9.1.1, 9.1.2, 9.1.3, 9.1.4, 9.1.x-dev, 9.2.x-dev].**
    - drupal/core-recommended 9.1.0-alpha1 requires symfony/routing v4.4.15 -> satisfiable by symfony/routing[v4.4.15].
    - drupal/core-recommended 9.1.0 requires symfony/routing v4.4.16 -> satisfiable by symfony/routing[v4.4.16].
    - drupal/core-recommended 9.1.0-beta1 requires symfony/routing v4.4.16 -> satisfiable by symfony/routing[v4.4.16].
    - drupal/core-recommended 9.1.0-rc1 requires symfony/routing v4.4.16 -> satisfiable by symfony/routing[v4.4.16].
    - drupal/core-recommended 9.1.0-rc2 requires symfony/routing v4.4.16 -> satisfiable by symfony/routing[v4.4.16].
    - drupal/core-recommended 9.1.0-rc3 requires symfony/routing v4.4.16 -> satisfiable by symfony/routing[v4.4.16].
    - drupal/core-recommended 9.1.1 requires symfony/routing v4.4.16 -> satisfiable by symfony/routing[v4.4.16].
    - drupal/core-recommended 9.1.2 requires symfony/routing v4.4.16 -> satisfiable by symfony/routing[v4.4.16].
    - drupal/core-recommended 9.1.3 requires symfony/routing v4.4.16 -> satisfiable by symfony/routing[v4.4.16].
    - drupal/core-recommended 9.1.4 requires symfony/routing v4.4.16 -> satisfiable by symfony/routing[v4.4.16].
    - drupal/core-recommended 9.1.x-dev requires symfony/routing v4.4.16 -> satisfiable by symfony/routing[v4.4.16].
    - drupal/core-recommended 9.2.x-dev requires symfony/routing v4.4.17 -> satisfiable by symfony/routing[v4.4.17].
    - symfony/routing v4.4.15 conflicts with symfony/config[v3.4.47].
    - symfony/routing v4.4.16 conflicts with symfony/config[v3.4.47].
    - symfony/routing v4.4.17 conflicts with symfony/config[v3.4.47].
    - Installation request for symfony/config (locked at v3.4.47) -> satisfiable by symfony/config[v3.4.47].

Thank you 
Dhina

**Comment by mxr576** [comment]
`composer show drupal/core-recommended`?

How about?
 `composer require drupal/swagger_ui_formatter:^3.0 --no-update && composer update drupal/swagger_ui_formatter drupal/core-recommended --with-dependencies`

**Comment by dhinakaran60** [comment]
![image](https://user-images.githubusercontent.com/65781478/107353394-fd588980-6af2-11eb-911a-340bcd9585c6.png)
![image](https://user-images.githubusercontent.com/65781478/107354181-dbabd200-6af3-11eb-932b-d2cdc19a1709.png)

**Comment by mxr576** [comment]
okay, so the problem is that your project is not using `drupal/core-recommended` package which a best practice, please update the project before you would update Swagger UI FF.
https://www.drupal.org/docs/updating-drupal/migrating-the-composer-project-for-drupal-earlier-than-880

**Comment by dhinakaran60** [comment]
Let me check . Thank you

**Comment by mxr576** [comment]
hm, it seems we caught an Drupal.org packagist bug...
https://www.drupal.org/project/drupal/issues/3197662

**Comment by mxr576** [comment]
@dhinakaran60 we created a new release that fixes the above mentioned Drupal packaging issue, please try again. (`drupal/core-recommended` is still a requirement)

**Comment by dhinakaran60** [comment]
@mxr576 thx
