### ISSUE TITLE
Bearer Token input on the popup dynamically 

### ISSUE THREAD

**Issue by dhinakaran60** [Pronovix/swagger_ui_formatter#67]
I need to generate the input bearer token on the popup irrespective of the spec uploaded. Which means in all cases i need bearerAuth (http, Bearer) input type in the popup. I found few reference in .NET technology but not on swagger-UI library itself. Is it possible and recommended? Can you please help on this? Using Swagger UI - 3.0

![image](https://user-images.githubusercontent.com/65781478/113880652-4cf8c000-97d9-11eb-930f-874fd872afa5.png)

https://mattfrear.com/2018/07/21/add-an-authorization-header-to-your-swagger-ui-with-swashbuckle-revisited/
https://ppolyzos.com/2017/10/30/add-jwt-bearer-authorization-to-swagger-and-asp-net-core/

**Comment by mxr576** [comment]
Sorry, but answering this question is out of the scope of this module.
