### ISSUE TITLE
CSS problem after update

### ISSUE THREAD

**Issue by axel584** [Pronovix/swagger_ui_formatter#68]
Hi,
I've updated the drupal and the swagger_ui_formatter module and the exemple value area become grey : 
![image](https://user-images.githubusercontent.com/1334088/116885375-1a9b8080-ac28-11eb-9f7d-793af2e1315e.png)

(before it was light yellow).

If I inspect the element, I see before the update : 
![image](https://user-images.githubusercontent.com/1334088/116885609-5afafe80-ac28-11eb-8a9c-7ddd7ddf401e.png)

and after the update : 
![image](https://user-images.githubusercontent.com/1334088/116885650-69e1b100-ac28-11eb-91c4-fb4736da663b.png)

The problem seem to be this `background: rgb(51, 51, 51);` 
But I have no idea where it come from.

How can I fix this problem ? I don't know if it's a "swagger", a "drupal" or a "swagger_ui_formatter" problem...

Thank you,

Axel

**Comment by mxr576** [comment]
Because this module only adds a connector JS between Drupal and Swagger UI, I would say it is a Swagger UI issue.
