### ISSUE TITLE
PHP 8.2 compatibility

### ISSUE THREAD

**Issue by mxr576** [Pronovix/swagger_ui_formatter#93]
FTR, PHP 8.2 compatibility can be only marked in a reliable way if our QA dependencies, mainly DrupalQA package, has support for that version.

See related story with PHP 8.0 when DrupalQA's minimum requirement for PHP 8.1 in #90.

**Comment by darianalexisortiz** [comment]
@mxr576 Hi, any news regarding this? thank you

**Comment by mxr576** [comment]
We are currently focusing on Drupal 10 upgrades. We have no official schedule yet for testing and flagging our packages as PHP 8.2 or 8.3 compatible yet.

Btw, the adaptation of PHP 8.2 still looks surprisingly low. https://packagist.org/php-statistics?ref=blog.packagist.com

![image](https://github.com/Pronovix/swagger_ui_formatter/assets/1755573/7ef3f99a-3002-4982-9142-02826a7aae42)

It is a bit better if we remove EOL-d versions :see_no_evil: 
![image](https://github.com/Pronovix/swagger_ui_formatter/assets/1755573/5af3ca12-964f-40b6-8215-73f14dea6a25)

**Comment by dpagini** [comment]
I would also like to request compatible PHP versions be bumped up here. This is one of the only contrib projects blocking my projects moving to PHP 8.2.

**Comment by SHUHAIB-AREEKKAN** [comment]
For me too this project blocks the to PHP 8.2

**Comment by somdebdasgupta** [comment]
@mxr576 - Any further update on the PHP 8.2 compatibility of this module? It is a blocker while upgrading to PHP 8.2.

Thanks in advance!

**Comment by mxr576** [comment]
Testing and flagging PHP 8.2 and maybe PHP 8.3 compatibility at the same is on our Q2 roadmap currently.

**Comment by Cleets** [comment]
This is also a blocker to PHP 8.2 as well. is that Q2 roadmap public so I can provide reference?

**Comment by mxr576** [comment]
Unfortunately it is not public,

**Comment by somdebdasgupta** [comment]
@mxr576 - We know the Q2 roadmap is not public, but is it possible to provide an idea, tentatively around which time in Q2, the new version of this module can be expected to release?

**Comment by mxr576** [comment]
#100 has PHP 8.2 support added. Under review. :100:

**Comment by mxr576** [comment]
Just got the news :O :grimacing: 

> The changes will apply immediately on the all currently supported branches from PHP 8.2. It also means that PHP 8.1 would get an extra year of security fixes if the proposal is accepted.

https://wiki.php.net/rfc/release_cycle_update
